### ISSUE TITLE
Error on fresh build regarding illegal character paths

### ISSUE THREAD

**Issue by viion** [liinko/FFXIV_TexTools2#12]
Downloaded the repository, did a fresh build and get:

```
System.Windows.Markup.XamlParseException: 'The invocation of the constructor on type 'FFXIV_TexTools2.MainWindow' that matches the specified binding constraints threw an exception.' Line number '10' and line position '5'. ---> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.Path.GetFileNameWithoutExtension(String path)
   at FFXIV_TexTools2.IO.ExdReader.MakeHUDList() in C:\Users\Josh\Desktop\tt2\FFXIV_TexTools2\IO\ExdReader.cs:line 494
   at FFXIV_TexTools2.IO.ExdReader.MakeUIList() in C:\Users\Josh\Desktop\tt2\FFXIV_TexTools2\IO\ExdReader.cs:line 74
   at FFXIV_TexTools2.IO.ExdReader.GetEXDData() in C:\Users\Josh\Desktop\tt2\FFXIV_TexTools2\IO\ExdReader.cs:line 39
   at FFXIV_TexTools2.ViewModel.MainViewModel.FillTree() in C:\Users\Josh\Desktop\tt2\FFXIV_TexTools2\ViewModel\MainViewModel.cs:line 449
   at FFXIV_TexTools2.ViewModel.MainViewModel..ctor() in C:\Users\Josh\Desktop\tt2\FFXIV_TexTools2\ViewModel\MainViewModel.cs:line 216
   at FFXIV_TexTools2.MainWindow..ctor() in C:\Users\Josh\Desktop\tt2\FFXIV_TexTools2\MainWindow.xaml.cs:line 45
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FFXIV_TexTools2.App.Main()
```

Also is there a way to disable update check?

**Comment by viion** [comment]
If I manage to get past this bit, it fails further by trying to read index files from `C:/` even if it found a legitimate FFXIV install path, and starts copying bits to `C:/` unsure why

![weirdpath](https://user-images.githubusercontent.com/270800/37053078-1cb78c44-2173-11e8-9714-3e1b9df46c22.png)
![weirdpath2](https://user-images.githubusercontent.com/270800/37053094-2a1029fa-2173-11e8-86ea-ec71f747bd66.png)

These error boxes are hidden behind the big "New Update Available!" box, so I have to use Alt+Space to move them out from behind lol

**Comment by viion** [comment]
Got most of this fixed and the tool compiling, was also able to disable the update check for debugging, so no longer an issue now!
